name = "edgetunnel-xhttp"
main = "_worker.js"
compatibility_date = "2025-11-04"
workers_dev = true
preview_urls = false
keep_vars = true

[placement]
region = "aws:ap-southeast-1"

[[routes]]
pattern = "ed.dys.qzz.io"
custom_domain = true

[[routes]]
pattern = "ed2.dys.qzz.io"
custom_domain = true

[[kv_namespaces]]
binding = "KV"
id = "fd40b1baccb8469ca918d0cc9495c3c3"